package cad;

import cad.util.Conecta;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigoapolinaro
 */
public class CadAluno extends javax.swing.JFrame {
    
    Conecta conecta_aluno;
    int navega = 0;
   
    public CadAluno() {
        initComponents();
        setLocationRelativeTo(null);
        
        conecta_aluno = new Conecta();
        conecta_aluno.conecta();
        // conecta_aluno.executeSQL("select * from alunos");
        conecta_aluno.executeSQL("select codigo,nome,cidade,estado,telefone,"
                    + "nota1,nota2,nota3,nota4,(nota1+nota2+nota3+nota4)"
                    + "/4 as media from alunos");
        try {
            
            conecta_aluno.resultSet.first();
                
                tf_codigo.setText(conecta_aluno.resultSet.getString("codigo"));
                tf_nome.setText(conecta_aluno.resultSet.getString("nome"));
                tf_cidade.setText(conecta_aluno.resultSet.getString("cidade"));
                tf_estado.setText(conecta_aluno.resultSet.getString("estado"));
                tf_telefone.setText(conecta_aluno.resultSet.getString("telefone"));
                
                tf_nota1.setText(conecta_aluno.resultSet.getString("nota1"));
                tf_nota2.setText(conecta_aluno.resultSet.getString("nota2"));
                tf_nota3.setText(conecta_aluno.resultSet.getString("nota3"));
                tf_nota4.setText(conecta_aluno.resultSet.getString("nota4"));
                
                float media = Float.parseFloat(conecta_aluno.resultSet.getString
                        ("media"));
                tf_media.setText(""+media);
        
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não localizou dados" + erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_estado = new javax.swing.JTextField();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        tf_cidade = new javax.swing.JTextField();
        tf_telefone = new javax.swing.JTextField();
        tf_nota1 = new javax.swing.JTextField();
        tf_nota2 = new javax.swing.JTextField();
        tf_nota4 = new javax.swing.JTextField();
        tf_media = new javax.swing.JTextField();
        tf_nota3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bt_novo = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_calcular = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        bt_ultimoRg = new javax.swing.JButton();
        bt_primeiroRg = new javax.swing.JButton();
        bt_proximo = new javax.swing.JButton();
        bt_anterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Aluno");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Cidade");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("MÉDIA");

        tf_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_estadoActionPerformed(evt);
            }
        });

        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        tf_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cidadeActionPerformed(evt);
            }
        });

        tf_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefoneActionPerformed(evt);
            }
        });

        tf_nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nota1ActionPerformed(evt);
            }
        });

        tf_nota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nota2ActionPerformed(evt);
            }
        });

        tf_nota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nota4ActionPerformed(evt);
            }
        });

        tf_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mediaActionPerformed(evt);
            }
        });

        tf_nota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nota3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Telefone");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Nota 1");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Nota 2");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Nota 3");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Nota 4");

        bt_novo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_novo.setText("Novo");
        bt_novo.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_excluir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_excluir.setText("Excluir");
        bt_excluir.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_salvar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_calcular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_calcular.setText("Calcular");
        bt_calcular.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        bt_sair.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_sair.setText("Sair");
        bt_sair.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        bt_ultimoRg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_ultimoRg.setText(">>");
        bt_ultimoRg.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_ultimoRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimoRgActionPerformed(evt);
            }
        });

        bt_primeiroRg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_primeiroRg.setText("<<");
        bt_primeiroRg.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_primeiroRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_primeiroRgActionPerformed(evt);
            }
        });

        bt_proximo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_proximo.setText(">");
        bt_proximo.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proximoActionPerformed(evt);
            }
        });

        bt_anterior.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bt_anterior.setText("<");
        bt_anterior.setPreferredSize(new java.awt.Dimension(113, 34));
        bt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_primeiroRg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_ultimoRg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(tf_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(tf_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(tf_media, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5))))))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel6)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ultimoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_primeiroRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_media, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(280, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_estadoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cidadeActionPerformed

    private void tf_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefoneActionPerformed

    private void tf_nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nota1ActionPerformed

    private void tf_nota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nota2ActionPerformed

    private void tf_nota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nota4ActionPerformed

    private void tf_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mediaActionPerformed

    private void tf_nota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nota3ActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        
        String sqlinsert = "insert into alunos (nome, cidade, estado, telefone,"
                + " nota1, nota2, nota3, nota4) values('"
                
                    + tf_nome.getText() + "','"
                    + tf_cidade.getText() + "','"
                    + tf_estado.getText() + "','"
                    + tf_telefone.getText() + "','"
                    + tf_nota1.getText() + "','"
                    + tf_nota2.getText() + "','"
                    + tf_nota3.getText() + "','"
                    + tf_nota4.getText() + "')";
        try {
            
            conecta_aluno.statement.executeUpdate(sqlinsert);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso");
            conecta_aluno.resultSet = conecta_aluno.statement.executeQuery
                        // ("Select * from alunos");
            ("select codigo,nome,cidade,estado,telefone,nota1,"
                + "nota2,nota3,nota4,"
                    + "(nota1+nota2+nota3+nota4)/4 as media from alunos");
            conecta_aluno.resultSet.first();
            mostrar_dados();
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog
                    (null, "Erro ao tentar gravar o registro" + erro);
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        float r = 0, a = 0, b = 0, c = 0, d = 0;
        a = Float.parseFloat(tf_nota1.getText());
        b = Float.parseFloat(tf_nota2.getText());
        c = Float.parseFloat(tf_nota3.getText());
        d = Float.parseFloat(tf_nota4.getText());
        
        r = (a + b + c + d) / 4;
        
        tf_media.setText("" + r);
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?",
                "Atenção", JOptionPane.YES_OPTION)==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proximoActionPerformed
        
        try {
            conecta_aluno.resultSet.next();
            mostrar_dados();
            navega = 2;
        
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não existe mais registro"+erro);
        }
    }//GEN-LAST:event_bt_proximoActionPerformed

    private void bt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anteriorActionPerformed
        
        try {
            conecta_aluno.resultSet.previous();
            mostrar_dados();
            navega = 1;
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não existe mais registro"+erro);
        }
    }//GEN-LAST:event_bt_anteriorActionPerformed

    private void bt_ultimoRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimoRgActionPerformed
        
        try {
            conecta_aluno.resultSet.last();
            mostrar_dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Este é último registro"+erro);
        }
    }//GEN-LAST:event_bt_ultimoRgActionPerformed

    private void bt_primeiroRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_primeiroRgActionPerformed
        
        try {
            conecta_aluno.resultSet.first();
            mostrar_dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Esse é o primeiro registro"+erro);
        }
    }//GEN-LAST:event_bt_primeiroRgActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        
        tf_nome.setText("");
        tf_cidade.setText("");
        tf_estado.setText("");
        tf_telefone.setText("");
        tf_nota1.setText("");
        tf_nota2.setText("");
        tf_nota3.setText("");
        tf_nota4.setText("");
        tf_media.setText("");
        
        tf_nome.requestFocus();
        tf_codigo.setEditable(false);
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        
        try {
            String sql = "Select * from alunos where codigo = "
                    + "" + tf_codigo.getText();
            
            conecta_aluno.executeSQL(sql);
            conecta_aluno.resultSet.first();
            
            String nome = "Excluir o aluno: "+conecta_aluno.resultSet.getString(
                    "nome")+(" ?");
            
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome,
                    "Excluir"
                    + " aluno", JOptionPane.YES_NO_OPTION);
            
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                
                sql = "DELETE FROM alunos where codigo ="+tf_codigo.getText();
                int conseguiu_excluir = conecta_aluno.statement.executeUpdate(sql);
                if (conseguiu_excluir == 1) {
                    JOptionPane.showMessageDialog(null, 
                            "Aluno excluido com sucesso");
                    conecta_aluno.executeSQL("select * from alunos");
                    conecta_aluno.resultSet.first();
                    mostrar_dados();
                }
            } 
        } 
            
        catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,
                    "Não foi possível excluir registro");
        }
        
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        
        String sqlupdate = "update alunos set nome='"
                + tf_nome.getText() + "',cidade='"
                + tf_cidade.getText() + "',estado='"
                + tf_estado.getText() + "',telefone='"
                + tf_telefone.getText() + "',nota1='"
                + tf_nota1.getText() + "',nota2='"
                + tf_nota2.getText() + "',nota3='"
                + tf_nota3.getText() + "',nota4='"
                + tf_nota4.getText() + "'where codigo="
                + tf_codigo.getText() +";";
        try {
            
            conecta_aluno.statement.executeUpdate(sqlupdate);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
            conecta_aluno.resultSet = conecta_aluno.statement.executeQuery
                        // ("Select * from alunos";
                        ("select codigo,nome,cidade,estado,telefone,nota1,"
                    + "nota2,nota3,nota4, (nota1+nota2+nota3+nota4)"
                        + "/4 as media from alunos");
            conecta_aluno.resultSet.first();
            mostrar_dados();
        } 
            catch (SQLException erro) {
                JOptionPane.showMessageDialog(null,
                        "Erro ao tentar gravar o registro" + erro);
            }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_anterior;
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_primeiroRg;
    private javax.swing.JButton bt_proximo;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_ultimoRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_estado;
    private javax.swing.JTextField tf_media;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nota1;
    private javax.swing.JTextField tf_nota2;
    private javax.swing.JTextField tf_nota3;
    private javax.swing.JTextField tf_nota4;
    private javax.swing.JTextField tf_telefone;
    // End of variables declaration//GEN-END:variables


    public void mostrar_dados() {

        try {

            tf_codigo.setText(conecta_aluno.resultSet.getString("codigo"));
            tf_nome.setText(conecta_aluno.resultSet.getString("nome"));
            tf_cidade.setText(conecta_aluno.resultSet.getString("cidade"));
            tf_estado.setText(conecta_aluno.resultSet.getString("estado"));
            tf_telefone.setText(conecta_aluno.resultSet.getString("telefone"));
            tf_nota1.setText(conecta_aluno.resultSet.getString("nota1"));
            tf_nota2.setText(conecta_aluno.resultSet.getString("nota2"));
            tf_nota3.setText(conecta_aluno.resultSet.getString("nota3"));
            tf_nota4.setText(conecta_aluno.resultSet.getString("nota4"));
            float media = Float.parseFloat(conecta_aluno.resultSet.getString
                    ("media"));
            tf_media.setText("" + media);
        }
            catch (SQLException erro) {
                if (navega == 1)
                    JOptionPane.showMessageDialog(null, 
                            "Não existem Registro Anteriores");
                else if (navega == 2) 
                    JOptionPane.showMessageDialog(null,
                            "Esse é o Último Registro");
                else
                    JOptionPane.showMessageDialog(null, 
                            "Não localizou os dados" + erro);
                navega = 0;
            }
    }

}